[project]
name = "test-sapsan"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.124.0",
    "langchain>=1.1.3",
    "pydantic>=2.12.5",
    "python-multipart>=0.0.20",
]
